// Package blueprint provides types and functions for parsing Aiken's plutus.json
// (CIP-0057 Plutus Blueprint) and generating Go code for type-safe datums,
// redeemers, and validators.
package blueprint

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// Blueprint represents a CIP-0057 Plutus Blueprint generated by Aiken.
type Blueprint struct {
	Preamble    Preamble           `json:"preamble"`
	Validators  []Validator        `json:"validators"`
	Definitions map[string]*Schema `json:"definitions"`
}

// Preamble contains metadata about the Aiken project.
type Preamble struct {
	Title         string   `json:"title"`
	Description   string   `json:"description"`
	Version       string   `json:"version"`
	PlutusVersion string   `json:"plutusVersion"`
	Compiler      Compiler `json:"compiler"`
	License       string   `json:"license"`
}

// Compiler contains information about the Aiken compiler version.
type Compiler struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// Validator represents a compiled Plutus validator/script.
type Validator struct {
	Title        string      `json:"title"`
	Datum        *Parameter  `json:"datum,omitempty"`
	Redeemer     Parameter   `json:"redeemer"`
	Parameters   []Parameter `json:"parameters,omitempty"`
	CompiledCode string      `json:"compiledCode"`
	Hash         string      `json:"hash"`
}

// Parameter represents a datum, redeemer, or script parameter.
type Parameter struct {
	Title  string `json:"title,omitempty"`
	Schema Schema `json:"schema"`
}

// LoadBlueprint reads and parses a plutus.json file.
func LoadBlueprint(path string) (*Blueprint, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading blueprint file: %w", err)
	}

	var bp Blueprint
	if err := json.Unmarshal(data, &bp); err != nil {
		return nil, fmt.Errorf("parsing blueprint JSON: %w", err)
	}

	normalizeAikenGenerics(&bp)

	return &bp, nil
}

// normalizeAikenGenerics rewrites Aiken 1.1.22+ generic-type naming
// (List<X>, Option<X>, Tuple<<X,Y>>, Pairs<K,V>) to the legacy form
// (List$X, Option$X, Tuple$X_Y, Pairs$K_V) used throughout the generator.
// The legacy form contains only identifier-safe characters, so all the
// existing string-prefix detection in the generator keeps working.
func normalizeAikenGenerics(bp *Blueprint) {
	if len(bp.Definitions) > 0 {
		renamed := make(map[string]*Schema, len(bp.Definitions))
		for name, schema := range bp.Definitions {
			renamed[normalizeAikenName(name)] = schema
		}
		bp.Definitions = renamed
		for _, schema := range bp.Definitions {
			schema.normalizeRefs()
		}
	}
	for i := range bp.Validators {
		v := &bp.Validators[i]
		if v.Datum != nil {
			v.Datum.Schema.normalizeRefs()
		}
		v.Redeemer.Schema.normalizeRefs()
		for j := range v.Parameters {
			v.Parameters[j].Schema.normalizeRefs()
		}
	}
}

// normalizeAikenName converts a single definition name from the new Aiken
// generic notation to the legacy form. Idempotent on names that don't use
// angle brackets.
func normalizeAikenName(name string) string {
	if !strings.ContainsAny(name, "<>") {
		return name
	}
	head, args, ok := splitAikenGeneric(name)
	if !ok {
		return name
	}
	normArgs := make([]string, len(args))
	for i, a := range args {
		normArgs[i] = normalizeAikenName(strings.TrimSpace(a))
	}
	return head + "$" + strings.Join(normArgs, "_")
}

// splitAikenGeneric parses "Head<args...>" or "Tuple<<args...>>".
// Returns the head name, the (top-level) comma-separated args, and ok=true
// if the input matches the generic-notation shape.
func splitAikenGeneric(name string) (head string, args []string, ok bool) {
	open := strings.Index(name, "<")
	if open <= 0 || !strings.HasSuffix(name, ">") {
		return "", nil, false
	}
	head = name[:open]
	inner := name[open+1 : len(name)-1]
	// Tuple uses an extra inner <...> layer (Aiken renders the tuple type
	// itself as <X,Y,...>): Tuple<<X,Y>>.
	if head == "Tuple" && strings.HasPrefix(inner, "<") && strings.HasSuffix(inner, ">") {
		inner = inner[1 : len(inner)-1]
	}
	args = splitTopLevelCommas(inner)
	return head, args, true
}

// splitTopLevelCommas splits s on commas that are not nested inside <...>.
func splitTopLevelCommas(s string) []string {
	var parts []string
	depth := 0
	last := 0
	for i, r := range s {
		switch r {
		case '<':
			depth++
		case '>':
			if depth > 0 {
				depth--
			}
		case ',':
			if depth == 0 {
				parts = append(parts, s[last:i])
				last = i + 1
			}
		}
	}
	parts = append(parts, s[last:])
	return parts
}

